# Hardware configuration for virtual machine
# Generated by nixos-generate-config
#
# To generate your actual hardware config, run:
# nixos-generate-config --show-hardware-config > hosts/vm/hardware.nix

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # Boot configuration for VM
  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # File systems
  # REPLACE THESE WITH YOUR ACTUAL UUIDs FROM nixos-generate-config
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/XXXX-XXXX";
    fsType = "vfat";
  };

  # Swap (optional for VM)
  # swapDevices = [ ];

  # Networking
  networking.useDHCP = lib.mkDefault true;

  # CPU configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
